version: 2
formats: ["pdf", "html"]

build:
  image: latest

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
