version: 2
formats: []

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - pip install .[all] .[docs]
      - python3 ./docs/scripts/generate_autodoc.py
