# This is a basic workflow to help you get started with Actions

name: Build documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: '3.8' 
    - name: Install requirements
      run: |
        pip install .[docs]
        pip install .[all]
    - name: Build html & latex
      run: cd docs && make html && make latex
    - name: Build pdf
      uses: dante-ev/latex-action@edge
      with:
        working_directory: docs/build/latex/
        root_file: discordadvertisementframework.tex

