name: Publish to PyPi

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os[0]}}

    strategy:
      matrix:
        os: 
        - [ubuntu-latest, manylinux_x86_64]
        - [macos-12, macosx_x86_64]
        - [windows-2019, win_amd64]
        python: ["cp38", "cp39", "cp310"]  # "pp39"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build cibuildwheel

    - name: Build wheels
      uses: pypa/cibuildwheel@0ecddd92b62987d7a2ae8911f4bb8ec9e2e4496a # v2.13.1
      env:
        CIBW_BUILD: ${{ matrix.python }}-${{ matrix.os[1] }}

    - name: Build source
      if: ${{matrix.python == 'cp38'}} and ${{matrix.os[0] == 'ubuntu-latest'}}
      run: |
        python -m build --sdist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@f5622bde02b04381239da3573277701ceca8f6a0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
